Backup

diff --git a/cli/Makefile b/cli/Makefile
--- a/cli/Makefile
+++ b/cli/Makefile
@@ -3,68 +3,54 @@ SRC_DIR := src
 INCLUDE_DIR := include
 BUILD_DIR := build
 
-SRC := $(shell find $(SRC_DIR) -type f -name '*.cpp')
-INCLUDE := $(shell find $(INCLUDE_DIR) -type f -name '*.hpp')
-
 CXX ?= g++
-ARCH ?= native
-CXX_FLAGS := -std=c++20 \
-             -Wall \
-             -O3 \
-             -march=$(ARCH) \
-             -flto=auto \
-             -funroll-loops \
-             -ffast-math \
-             -fomit-frame-pointer \
-             -fno-rtti \
-             -I$(INCLUDE_DIR) \
-             -I$(INCLUDE_DIR)/shoid/uWebSockets
+CXX_FLAGS ?= -std=c++17 -Wall -Wextra -Wpedantic -MMD -MP -I$(INCLUDE_DIR)/shoid/uWebSockets -Llibs/$(PLATFORM_NAME)
+LD_FLAGS ?= -lz -lcrypto -luSockets
 
-LD_FLAGS := -lpthread -lcrypto -lz -luv -L./libs -Wl,-Bstatic -luSockets -Wl,-Bdynamic
+RELEASE_FLAGS ?= -O3 -DNDEBUG -static-libstdc++ -static-libgcc
+
+PLATFORM_NAME ?= linux-x32_64
+include toolchains/$(PLATFORM_NAME).mk
+
+SOURCES := $(shell find $(SRC_DIR) -type f -name "*.cpp")
+OBJECTS := $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/$(PLATFORM_NAME)/%.o,$(SOURCES))
+DEPS := $(OBJECTS:.o=.d)
+
+LIBS ?= $(wildcard ./libs/$(PLATFORM_NAME)/*.a)
+
+all: CXX_FLAGS += -g
+all: $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME)
+
+release: CXX_FLAGS += $(RELEASE_FLAGS)
+release: clean $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME)
+
+$(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME): $(OBJECTS)
+	@mkdir -p $(dir $@)
+	$(CXX) $(CXX_FLAGS) -I$(INCLUDE_DIR) -o $@ $^ $(LIBS) $(LD_FLAGS)
+
+$(BUILD_DIR)/$(PLATFORM_NAME)/%.o: $(SRC_DIR)/%.cpp
+	@mkdir -p $(dir $@)
+	$(CXX) $(CXX_FLAGS) -I$(INCLUDE_DIR) -c $< -o $@
+
+-include $(DEPS)
+
+test:
+	g++ -shared -fPIC test/main.cpp -o test/arch.so -Iinclude
+	if ./build/linux-x32_64/xwm load ./test/arch.so this may be anything 2>/dev/null; then \
+		echo "All tests ran successfully"; \
+	else \
+		echo "Test failed with exit code $$?"; \
+	fi
 
 
-LINUX_BUILD_DIR := $(BUILD_DIR)/linux
-WIN_BUILD_DIR   := $(BUILD_DIR)/win
 
-LINUX_OBJ := $(patsubst $(SRC_DIR)/%.cpp,$(LINUX_BUILD_DIR)/%.o,$(SRC))
-WIN_OBJ   := $(patsubst $(SRC_DIR)/%.cpp,$(WIN_BUILD_DIR)/%.o,$(SRC))
-
-# Linux build
-# ----------------------------------------
-$(LINUX_BUILD_DIR)/$(PROJECT_NAME): $(LINUX_OBJ) | $(LINUX_BUILD_DIR) $(INCLUDE)
-	$(CXX) -o $@ $^ $(LD_FLAGS)
-
-$(LINUX_BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(INCLUDE) $(LINUX_BUILD_DIR)
-	@ mkdir -p $(dir $@)
-	$(CXX) $(CXX_FLAGS) -c $< -o $@
-
-$(LINUX_BUILD_DIR):
-	mkdir -p $@
-
-linux: $(LINUX_BUILD_DIR)/$(PROJECT_NAME)
-	@echo "Linux build complete: $<"
-
-# Windows build
-# ----------------------------------------
-$(WIN_BUILD_DIR)/$(PROJECT_NAME).exe: $(WIN_OBJ) | $(WIN_BUILD_DIR) $(INCLUDE)
-	x86_64-w64-mingw32-g++ -o $@ $^ -static -static-libgcc -static-libstdc++ -lpthread
-
-$(WIN_BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(INCLUDE) $(WIN_BUILD_DIR)
-	@ mkdir -p $(dir $@)
-	x86_64-w64-mingw32-g++ $(CXX_FLAGS) -c $< -o $@
-
-$(WIN_BUILD_DIR):
-	mkdir -p $@
-
-win: $(WIN_BUILD_DIR)/$(PROJECT_NAME).exe
-	@echo "Windows build complete: $<"
-
-# Phony
-# ----------------------------------------
 clean:
 	rm -rf $(BUILD_DIR)
 
-install_linux:
-	cp $(LINUX_BUILD_DIR)/$(PROJECT_NAME) /usr/local/bin/$(PROJECT_NAME)
+run: all
+	./$(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME)
 
-.PHONY: linux win clean install_linux
+install: release
+	sudo cp $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME) /usr/local/bin/
+
+.PHONY: all release clean run test
